### ISSUE TITLE
Maximum call stack size exceeded when running sanity-template build

### ISSUE THREAD

**Issue by OnecodexGitHubAdmin** [sanity-io/sanity-template#15]
Hello everybody

I am creating a starter template for sanity using angular, scully.io and sanity inside an nx workspace.
When running the command to build the template:
`npx sanity-template build --template-values template-values-development.json`

I get the following maximum call stack error:
`
RangeError: Maximum call stack size exceeded
    at Object.resolve (path.js:127:10)
    at resolveIgnores (C:\Users\mwolf\Documents\VisualStudioCode\sanity-template-angular-website\node_modules\sanity-template\dist\commands\utils\fs.js:67:39)
    at resolveIgnores (C:\Users\mwolf\Documents\VisualStudioCode\sanity-template-angular-website\node_modules\sanity-template\dist\commands\utils\fs.js:68:44)
    at resolveIgnores (C:\Users\mwolf\Documents\VisualStudioCode\sanity-template-angular-website\node_modules\sanity-template\dist\commands\utils\fs.js:68:44)
    at resolveIgnores (C:\Users\mwolf\Documents\VisualStudioCode\sanity-template-angular-website\node_modules\sanity-template\dist\commands\utils\fs.js:68:44)
    at resolveIgnores (C:\Users\mwolf\Documents\VisualStudioCode\sanity-template-angular-website\node_modules\sanity-template\dist\commands\utils\fs.js:68:44)
    at resolveIgnores (C:\Users\mwolf\Documents\VisualStudioCode\sanity-template-angular-website\node_modules\sanity-template\dist\commands\utils\fs.js:68:44)
    at resolveIgnores (C:\Users\mwolf\Documents\VisualStudioCode\sanity-template-angular-website\node_modules\sanity-template\dist\commands\utils\fs.js:68:44)
    at resolveIgnores (C:\Users\mwolf\Documents\VisualStudioCode\sanity-template-angular-website\node_modules\sanity-template\dist\commands\utils\fs.js:68:44)
    at resolveIgnores (C:\Users\mwolf\Documents\VisualStudioCode\sanity-template-angular-website\node_modules\sanity-template\dist\commands\utils\fs.js:68:44)
`

This happens in the file:
sanity-template\dist\commands\utils\fs.js
in the resolveIgnores function 

I temporary solvet this by just returning an empoty array in this function (which I guess is not supposed to do).

Maybe it's because of having all of this inside an nx workspace and there are more than one .gitignore files or only on my win10 64 bit machine.

Please let me know if you need more information.
Best regards
Magnus

**Comment by bjoerge** [comment]
Thanks! Fixed in v2.4.3
